In [2]:
import numpy as np

allocated_matrix = np.array([[0, 1, 0], [2, 0, 0], [3, 0, 2], [2, 1, 1], [0, 0, 2]])
max_matrix = np.array([[7, 5, 3], [3, 2, 2], [9, 0, 2], [2, 2, 2,], [4, 3, 3]])
work_matrix = np.array([[3, 3, 2]])
safe_order = []
need_matrix = max_matrix - allocated_matrix
print("Allocated Matrix\n",allocated_matrix,"\n------------\nMax Matrix\n", \
      max_matrix, "\n------------\nWork Matrix\n", work_matrix, \
      "\n------------\nNeed Matrix\n", need_matrix,"\n------------\n")
#comparison = need_matrix <= work_matrix
#comparison

Allocated Matrix
 [[0 1 0]
 [2 0 0]
 [3 0 2]
 [2 1 1]
 [0 0 2]] 
------------
Max Matrix
 [[7 5 3]
 [3 2 2]
 [9 0 2]
 [2 2 2]
 [4 3 3]] 
------------
Work Matrix
 [[3 3 2]] 
------------
Need Matrix
 [[7 4 3]
 [1 2 2]
 [6 0 0]
 [0 1 1]
 [4 3 1]] 
------------



In [3]:
need_matrix <= work_matrix

array([[False, False, False],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [4]:
number_of_processes = allocated_matrix.shape[0]
number_of_processes

5

In [5]:
number_of_resources = allocated_matrix.shape[1]
number_of_resources

3

In [6]:
number_of_processes = len(need_matrix)
number_of_processes

5

In [7]:
while(number_of_processes>0):
  for process_number, need_resource in enumerate(need_matrix):
    #print("\n", work_matrix)
    if (need_matrix[process_number] <= work_matrix).all() and process_number not in safe_order:
      work_matrix += allocated_matrix[process_number]
      safe_order.append(process_number)
      number_of_processes = number_of_processes-1
    #print(process_number,": ", need_resource,"\n------------\n")

In [8]:
work_matrix

array([[10,  5,  7]])

In [ ]:
safe_order